import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import { loadConfigFromCliOpts } from './config';
import { loadOpenApiSuite } from './plugins/openapi-loader';
import type { TestCase } from './types';

function toFileSlug(text: string): string {
  const slug = text
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return slug || 'openapi-suite';
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => pad + line)
    .join('\n');
}

const PLACEHOLDER_MARKER = '__SPECTEST_REGENERATE_PLACEHOLDERS__';
const PLACEHOLDER_TOKEN = /\{\{(uuid|timestamp|shortId)\}\}/;

// Matches src/helpers.ts's regenerateExampleData: re-rolls `{{uuid}}`/
// `{{timestamp}}`/`{{shortId}}` tokens in a request's url/headers/data right
// before each send. Inlined here (rather than imported) so the scaffold
// stays runnable standalone, independent of whichever spectest version is
// installed in the target project.
const REGENERATE_HELPER = `const __SPECTEST_PLACEHOLDER_GENERATORS = {
  uuid: () => crypto.randomUUID(),
  timestamp: () => String(Date.now()),
  shortId: () => Math.random().toString(36).slice(2, 10),
};
const __SPECTEST_PLACEHOLDER_PATTERN = /\\{\\{(uuid|timestamp|shortId)\\}\\}/g;
function __spectestResolvePlaceholders(value) {
  if (typeof value === 'string') {
    return value.replace(__SPECTEST_PLACEHOLDER_PATTERN, (_m, name) => __SPECTEST_PLACEHOLDER_GENERATORS[name]());
  }
  if (Array.isArray(value)) return value.map(__spectestResolvePlaceholders);
  if (value && typeof value === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = __spectestResolvePlaceholders(v);
    return out;
  }
  return value;
}
function __spectestRegenerateExampleData(config) {
  return {
    ...config,
    url: __spectestResolvePlaceholders(config.url),
    headers: __spectestResolvePlaceholders(config.headers),
    data: __spectestResolvePlaceholders(config.data),
  };
}
`;

function serializeTest(test: TestCase): string {
  const { beforeSend, postTest, ...serializable } = test;
  if (!beforeSend && !postTest) {
    const json = JSON.stringify(serializable, null, 2);
    // A test whose example still contains `{{uuid}}`/`{{timestamp}}`/
    // `{{shortId}}` (preserved by loadOpenApiSuite's preservePlaceholders
    // option) needs those re-rolled on every send, not just once at
    // generation time - otherwise re-running the file replays the exact
    // same value forever, which breaks "must not already exist" endpoints
    // like signup.
    if (PLACEHOLDER_TOKEN.test(json)) {
      const withMarker = JSON.stringify({ ...serializable, beforeSend: PLACEHOLDER_MARKER }, null, 2);
      return withMarker.replace(`"beforeSend": "${PLACEHOLDER_MARKER}"`, 'beforeSend: __spectestRegenerateExampleData');
    }
    return json;
  }
  const json = JSON.stringify(serializable, null, 2);
  const hookNames = [beforeSend && 'beforeSend', postTest && 'postTest'].filter(Boolean).join('/');
  return `${json}\n// TODO: this generated test had a ${hookNames} attached (from x-spectest or a links chain).\n// Re-attach the matching function from your spectest.config.js openapiHooks/openapiAuth here.`;
}

export async function generateOpenApiTests(openapiPath: string, outputDir: string, cfg: any): Promise<string[]> {
  const suite = await loadOpenApiSuite(openapiPath, cfg, { preservePlaceholders: true });
  await mkdir(outputDir, { recursive: true });
  const fileName = `${toFileSlug(suite.name)}.spectest.js`;
  const filePath = path.join(outputDir, fileName);
  const allTests = [...suite.setup, ...suite.tests, ...suite.teardown];
  const serializedTests = allTests.map((test) => serializeTest(test));
  const needsRegenerateHelper = serializedTests.some((json) => json.includes('__spectestRegenerateExampleData'));

  const body = `// AUTO-GENERATED by \`spectest generate openapi-tests\` from ${path.relative(process.cwd(), openapiPath)}.
// DO NOT EDIT: re-running the generator will overwrite this file.
${needsRegenerateHelper ? REGENERATE_HELPER : ''}export default {
  name: ${JSON.stringify(suite.name)},
  tests: [
${serializedTests.map((json) => indent(json, 4)).join(',\n')}
  ],
};
`;
  await writeFile(filePath, body, 'utf8');
  return [filePath];
}

function parseGenerateArgs(args: string[]): { openapiPath?: string; outputDir?: string; projectRoot?: string; configFile?: string } {
  const result: { openapiPath?: string; outputDir?: string; projectRoot?: string; configFile?: string } = {};
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === '--openapi') {
      result.openapiPath = args[i + 1];
      i += 1;
    } else if (arg === '--output') {
      result.outputDir = args[i + 1];
      i += 1;
    } else if (arg === '--dir') {
      result.projectRoot = args[i + 1];
      i += 1;
    } else if (arg === '--config') {
      result.configFile = args[i + 1];
      i += 1;
    }
  }
  return result;
}

export async function runGenerateCommand(argv: string[]): Promise<void> {
  // argv: [node, cli.js, 'generate', 'openapi-tests', ...flags]
  const subcommand = argv[3];
  if (subcommand !== 'openapi-tests') {
    console.error(`error: unknown 'generate' subcommand '${subcommand}'. Usage: spectest generate openapi-tests --openapi <path> --output <dir>`);
    process.exit(1);
  }

  const { openapiPath, outputDir, projectRoot, configFile } = parseGenerateArgs(argv.slice(4));
  if (!openapiPath || !outputDir) {
    console.error('usage: spectest generate openapi-tests --openapi <path> --output <dir>');
    process.exit(1);
  }

  const cfg = await loadConfigFromCliOpts({ projectRoot, configFile });
  const resolvedOpenapiPath = path.resolve(cfg.projectRoot as string, openapiPath);
  const resolvedOutputDir = path.resolve(cfg.projectRoot as string, outputDir);

  const written = await generateOpenApiTests(resolvedOpenapiPath, resolvedOutputDir, cfg);
  console.log(`[spectest] Wrote ${written.length} scaffold file(s):`);
  written.forEach((file) => console.log(`  - ${file}`));
}
