import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import { loadConfigFromCliOpts } from './config';
import { loadOpenApiSuite } from './plugins/openapi-loader';
import type { TestCase } from './types';

function toFileSlug(text: string): string {
  const slug = text
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return slug || 'openapi-suite';
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => pad + line)
    .join('\n');
}

function serializeTest(test: TestCase): string {
  const { beforeSend, postTest, ...serializable } = test;
  const json = JSON.stringify(serializable, null, 2);
  if (!beforeSend && !postTest) return json;
  const hookNames = [beforeSend && 'beforeSend', postTest && 'postTest'].filter(Boolean).join('/');
  return `${json}\n// TODO: this generated test had a ${hookNames} attached (from x-spectest or a links chain).\n// Re-attach the matching function from your spectest.config.js openapiHooks/openapiAuth here.`;
}

export async function generateOpenApiTests(openapiPath: string, outputDir: string, cfg: any): Promise<string[]> {
  const suite = await loadOpenApiSuite(openapiPath, cfg);
  await mkdir(outputDir, { recursive: true });
  const fileName = `${toFileSlug(suite.name)}.spectest.js`;
  const filePath = path.join(outputDir, fileName);
  const allTests = [...suite.setup, ...suite.tests, ...suite.teardown];

  const body = `// Generated by \`spectest generate openapi-tests\` from ${path.relative(process.cwd(), openapiPath)}.
// This is a one-time scaffold: edit freely, it will not be regenerated in place.
export default {
  name: ${JSON.stringify(suite.name)},
  tests: [
${allTests.map((test) => indent(serializeTest(test), 4)).join(',\n')}
  ],
};
`;
  await writeFile(filePath, body, 'utf8');
  return [filePath];
}

function parseGenerateArgs(args: string[]): { openapiPath?: string; outputDir?: string; projectRoot?: string; configFile?: string } {
  const result: { openapiPath?: string; outputDir?: string; projectRoot?: string; configFile?: string } = {};
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === '--openapi') {
      result.openapiPath = args[i + 1];
      i += 1;
    } else if (arg === '--output') {
      result.outputDir = args[i + 1];
      i += 1;
    } else if (arg === '--dir') {
      result.projectRoot = args[i + 1];
      i += 1;
    } else if (arg === '--config') {
      result.configFile = args[i + 1];
      i += 1;
    }
  }
  return result;
}

export async function runGenerateCommand(argv: string[]): Promise<void> {
  // argv: [node, cli.js, 'generate', 'openapi-tests', ...flags]
  const subcommand = argv[3];
  if (subcommand !== 'openapi-tests') {
    console.error(`error: unknown 'generate' subcommand '${subcommand}'. Usage: spectest generate openapi-tests --openapi <path> --output <dir>`);
    process.exit(1);
  }

  const { openapiPath, outputDir, projectRoot, configFile } = parseGenerateArgs(argv.slice(4));
  if (!openapiPath || !outputDir) {
    console.error('usage: spectest generate openapi-tests --openapi <path> --output <dir>');
    process.exit(1);
  }

  const cfg = await loadConfigFromCliOpts({ projectRoot, configFile });
  const resolvedOpenapiPath = path.resolve(cfg.projectRoot as string, openapiPath);
  const resolvedOutputDir = path.resolve(cfg.projectRoot as string, outputDir);

  const written = await generateOpenApiTests(resolvedOpenapiPath, resolvedOutputDir, cfg);
  console.log(`[spectest] Wrote ${written.length} scaffold file(s):`);
  written.forEach((file) => console.log(`  - ${file}`));
}
